# Site settings
title: Adi Utama
email: neogatotkaca@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    Sebagian dari isi kepalaku

# Build settings
markdown: kramdown
excerpt_separator: <!--more-->

# Plugins
gems:
  - jekyll-sitemap
